"""empty message

Revision ID: 20c541a203b2
Revises: caee14a2c6e4
Create Date: 2020-01-08 14:44:15.476528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20c541a203b2'
down_revision = 'caee14a2c6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('comment_id', table_name='papers')
    op.drop_column('papers', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('comment_id', 'papers', ['comment_id'], unique=True)
    # ### end Alembic commands ###
