"""empty message

Revision ID: 3456257c87f8
Revises: 20c541a203b2
Create Date: 2020-01-08 22:19:45.821775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3456257c87f8'
down_revision = '20c541a203b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('times', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'times')
    # ### end Alembic commands ###
