"""empty message

Revision ID: caee14a2c6e4
Revises: 989cbda00137
Create Date: 2020-01-07 22:47:25.772804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caee14a2c6e4'
down_revision = '989cbda00137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('idcard', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'admins', ['idcard'])
    op.add_column('students', sa.Column('idcard', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'students', ['idcard'])
    op.add_column('teachers', sa.Column('idcard', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'teachers', ['idcard'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'idcard')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'idcard')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'idcard')
    # ### end Alembic commands ###
