"""empty message

Revision ID: cd0a1fc98cee
Revises: 3456257c87f8
Create Date: 2020-01-08 23:58:30.412264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0a1fc98cee'
down_revision = '3456257c87f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_comments', sa.Column('times', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_comments', 'times')
    # ### end Alembic commands ###
